version: '3.6'
services:
  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
#    volumes:
#    - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ELASTIC_PASSWORD: test123
      xpack.security.enabled: 'true'
      discovery.type: single-node
    ports:
    - '9200:9200'
    - '9300:9300'
    networks:
      - elk_elk

  logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    volumes:
      - ./logstash/:/usr/share/logstash/pipeline:rw
      - /Users/chathuranga/MyDocuments/WAWN/official/elk/log:/app/logs
    depends_on:
      - elasticsearch
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk_elk

  kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=test123
    depends_on:
      - elasticsearch
    networks:
      - elk_elk

networks:
  elk_elk:
    external:
      name: elk_elk
