version: '3.6'
services:
  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    environment:
      ELASTIC_PASSWORD: ${ES_PASSWORD}
      xpack.security.enabled: 'true'
      discovery.type: single-node
    ports:
    - '9200:9200'
    - '9300:9300'
    networks:
      - hoov_elk_network

  logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    volumes:
      - ./logstash/:/usr/share/logstash/pipeline:rw
      - /Users/chathuranga/MyDocuments/WAWN/official/elk/log:/app/logs
    depends_on:
      - elasticsearch
    ports:
      - '9600:9600'
    networks:
      - hoov_elk_network

  kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${ES_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ES_PASSWORD}
    depends_on:
      - elasticsearch
    networks:
      - hoov_elk_network

networks:
  hoov_elk_network:
    driver: bridge

